import type { GetServerSideProps } from "next";

import Head from "next/head";
import styles from "../styles/Home.module.css";
import { MoviesService } from "../src/services/Movies.Service";
import { MovieInterface } from "../src/interfaces/movie.interface";
import Link from "next/link";
import { Header } from "../src/components/Header/Header";
import { useSaveInLclStrg } from "../src/lib/useSaveInLclStrg";
import { Footer } from "../src/components/Footer/Footer";

const Home = (props: any) => {
  const { movies } = props;
  return (
    <div className={styles.container}>
      <Head>
        <title>Nletfix | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        {movies.length ? (
          movies.map((el: MovieInterface) => (
            <Link href={"/movie/" + el.id} key={el.movie_title + el.id}>
              <a
                className={styles.movie_item}
                onClick={() => useSaveInLclStrg(el)}
              >
                <h2>{el.movie_title}</h2>
                <div className={styles.movie_wrap}>
                  <img
                    src={el.movie_image}
                    alt={el.movie_title}
                    className={styles.movie_image}
                  />
                  <div>
                    <div className={styles.flex}>
                      <p>Genre:</p>
                      <p>{el.movie_genre}</p>
                    </div>
                    <div>
                      <p>Description:</p>
                      <p>{el.movie_description}</p>
                    </div>
                  </div>
                </div>
              </a>
            </Link>
          ))
        ) : (
          <div>
            <h2>No results</h2>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await MoviesService.movies(context.query);
  return { props: { movies: res.data } };
};
